module.exports = {
  UPLOAD_SESSION_INITIATED: "UPLOAD_SESSION_INITIATED",
  CHUNK_CONFIRMED: "CHUNK_CONFIRMED",
  UPLOAD_COMPLETED: "UPLOAD_COMPLETED",
  DOWNLOAD_URL_GENERATED: "DOWNLOAD_URL_GENERATED",
  FILE_DELETED: "FILE_DELETED",
};
